### ISSUE TITLE
Error on installing with npm

### ISSUE THREAD

**Issue by rpvilo** [hcorta/react-echarts#1]
I was trying to install this ECharts library via npm but I'm getting this error on installation process:

`npm ERR! code EINVALIDTAGNAME`
`npm ERR! Invalid tag name "^>=15.0.0": Tags may not have any characters that encodeURIComponent encodes.`

Hopefully it's a quick fix!

**Comment by hcorta** [comment]
@rpvilo hi! Thanks for letting me know. I’ll fix this issue in a couple of days max. (I’m currently off with no access to my computer) . Sorry for the inconvenience 🙏

**Comment by hcorta** [comment]
@rpvilo v1.0.1 already on npm with the issue fixed.
